/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSubscriptionsRouteImport } from './routes/dashboard.subscriptions'
import { Route as DashboardProvidersRouteImport } from './routes/dashboard.providers'
import { Route as DashboardNewRouteImport } from './routes/dashboard.new'
import { Route as ApiPublicSubscriptionsRouteImport } from './routes/api/public/subscriptions'
import { Route as ApiPublicHooksCleanupSubscriptionsRouteImport } from './routes/api/public/hooks/cleanup-subscriptions'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubscriptionsRoute = DashboardSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProvidersRoute = DashboardProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNewRoute = DashboardNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicSubscriptionsRoute = ApiPublicSubscriptionsRouteImport.update({
  id: '/api/public/subscriptions',
  path: '/api/public/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCleanupSubscriptionsRoute =
  ApiPublicHooksCleanupSubscriptionsRouteImport.update({
    id: '/api/public/hooks/cleanup-subscriptions',
    path: '/api/public/hooks/cleanup-subscriptions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/dashboard/providers': typeof DashboardProvidersRoute
  '/dashboard/subscriptions': typeof DashboardSubscriptionsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/subscriptions': typeof ApiPublicSubscriptionsRoute
  '/api/public/hooks/cleanup-subscriptions': typeof ApiPublicHooksCleanupSubscriptionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/dashboard/providers': typeof DashboardProvidersRoute
  '/dashboard/subscriptions': typeof DashboardSubscriptionsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/subscriptions': typeof ApiPublicSubscriptionsRoute
  '/api/public/hooks/cleanup-subscriptions': typeof ApiPublicHooksCleanupSubscriptionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/dashboard/providers': typeof DashboardProvidersRoute
  '/dashboard/subscriptions': typeof DashboardSubscriptionsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/subscriptions': typeof ApiPublicSubscriptionsRoute
  '/api/public/hooks/cleanup-subscriptions': typeof ApiPublicHooksCleanupSubscriptionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/new'
    | '/dashboard/providers'
    | '/dashboard/subscriptions'
    | '/dashboard/'
    | '/api/public/subscriptions'
    | '/api/public/hooks/cleanup-subscriptions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/new'
    | '/dashboard/providers'
    | '/dashboard/subscriptions'
    | '/dashboard'
    | '/api/public/subscriptions'
    | '/api/public/hooks/cleanup-subscriptions'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/new'
    | '/dashboard/providers'
    | '/dashboard/subscriptions'
    | '/dashboard/'
    | '/api/public/subscriptions'
    | '/api/public/hooks/cleanup-subscriptions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicSubscriptionsRoute: typeof ApiPublicSubscriptionsRoute
  ApiPublicHooksCleanupSubscriptionsRoute: typeof ApiPublicHooksCleanupSubscriptionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/subscriptions': {
      id: '/dashboard/subscriptions'
      path: '/subscriptions'
      fullPath: '/dashboard/subscriptions'
      preLoaderRoute: typeof DashboardSubscriptionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/providers': {
      id: '/dashboard/providers'
      path: '/providers'
      fullPath: '/dashboard/providers'
      preLoaderRoute: typeof DashboardProvidersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/new': {
      id: '/dashboard/new'
      path: '/new'
      fullPath: '/dashboard/new'
      preLoaderRoute: typeof DashboardNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/subscriptions': {
      id: '/api/public/subscriptions'
      path: '/api/public/subscriptions'
      fullPath: '/api/public/subscriptions'
      preLoaderRoute: typeof ApiPublicSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cleanup-subscriptions': {
      id: '/api/public/hooks/cleanup-subscriptions'
      path: '/api/public/hooks/cleanup-subscriptions'
      fullPath: '/api/public/hooks/cleanup-subscriptions'
      preLoaderRoute: typeof ApiPublicHooksCleanupSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardNewRoute: typeof DashboardNewRoute
  DashboardProvidersRoute: typeof DashboardProvidersRoute
  DashboardSubscriptionsRoute: typeof DashboardSubscriptionsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardNewRoute: DashboardNewRoute,
  DashboardProvidersRoute: DashboardProvidersRoute,
  DashboardSubscriptionsRoute: DashboardSubscriptionsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicSubscriptionsRoute: ApiPublicSubscriptionsRoute,
  ApiPublicHooksCleanupSubscriptionsRoute:
    ApiPublicHooksCleanupSubscriptionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
